### ISSUE TITLE
ocsbincodec-java is not supported in Java 1.4

### ISSUE THREAD

**Issue by fjtc** [opencs/ocsbincodec-java#1]
It would be interesting to have support for Java 1.4.

**Comment by fjtc** [comment]
Right now, the current version is not compatible with Java 1.4 because it uses:
- JUnit 4;
- Annotations;
- for each loops;
- Classes java.lang.StringBuilder and java.util.Arrays;

In order to make it compatible, it will be necessary to replace those entries with Java 1.4 compatible ones.

**Comment by monoman** [comment]
Now it is compatible (non-verified on a real 1.4 VM)

**Comment by fjtc** [comment]
Tested on a real Java 1.4 VM. Unfortunately it does not work properly due to classpath differences. Furthermore, the backport to 1.4 implies a few drawbacks to newer versions of Java, specially the forced use of StringBuffer.

Given that I'll revert the code to the previous known version working version for Java 1.5 and create a new branch to hold the backport to 1.4.

**Comment by fjtc** [comment]
The initial changes to Java 1.4 are now in the branch Java-1.4. From now on, they will be separated entities.

**Comment by fjtc** [comment]
Artifact renamed to br.com.opencs:ocsbincodec-java-1.4. This version is still not working properly on a JVM 1.4.

**Comment by fjtc** [comment]
A new version updating the initial work of monoman is available on branch java-1.4. This version was tested with an actual Java 1.4.2_19 from Oracle and is working as expected. From now on, the main version and the Java 1.4 version will be kept on distinct branches in order to avoid disruption on the version control.
